# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_id', models.IntegerField()),
                ('problem_Statment', models.TextField(max_length=2000, verbose_name="This is the problem's text!")),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField()),
                ('result', models.TextField(max_length=2000, verbose_name='1 1 1')),
            ],
        ),
        migrations.CreateModel(
            name='Test_cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField()),
                ('test_cases', models.TextField(max_length=2000, verbose_name='3 1 2 2')),
            ],
        ),
    ]
