# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-02 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='problem_Statment',
            field=models.TextField(max_length=240, verbose_name="This is the problem's text!"),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.TextField(max_length=240, verbose_name='1 1 1'),
        ),
        migrations.AlterField(
            model_name='test_cases',
            name='test_cases',
            field=models.TextField(max_length=240, verbose_name='3 1 2 2'),
        ),
    ]
