# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_auto_20171102_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='problem_Statment',
        ),
        migrations.AddField(
            model_name='problems',
            name='problem_statement',
            field=models.TextField(default=django.utils.timezone.now, max_length=240),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.TextField(max_length=240),
        ),
        migrations.AlterField(
            model_name='test_cases',
            name='test_cases',
            field=models.TextField(max_length=240),
        ),
    ]
