# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_auto_20171103_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='problem_statement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='test_cases',
            name='test_cases',
            field=models.TextField(),
        ),
    ]
